'use client'

import type { ReactNode } from 'react'
import Link from 'next/link'
import { EnerBioButtonAccent, EnerBioButtonPrimary } from '@/components/ui/EnerBioButton'
import { servicePages } from '@/lib/data/servicePages'
import { useInView } from '@/lib/hooks/useInView'

const modes = [
  ['specific', 'Un servicio específico', 'Nos sumamos a tu proyecto donde nos necesites.', 'Ej: O&M de una central existente'],
  ['combined', 'Servicios combinados', 'Integramos dos o más departamentos según el alcance.', 'Ej: Ingeniería + Montaje'],
  ['integral', 'Todo el ciclo integral', 'Asumimos desde la prefactibilidad hasta la operación 24/7.', 'Ej: Modelo Vapor y Energía'],
]
const benefits = ['Sin CAPEX', 'Planta propiedad EnerBio', 'Contratos de largo plazo', 'Solo pagás consumo', 'Sin operación de tu parte', '100% renovable']

const icons: Record<string, ReactNode> = {
  specific: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M4 7h10M4 12h7M4 17h10"/><path d="M18 8v8M14 12h8"/></svg>,
  combined: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><rect x="3" y="4" width="8" height="8" rx="1"/><rect x="13" y="12" width="8" height="8" rx="1"/><path d="m11 8 4 4"/></svg>,
  integral: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 4v7h-7"/></svg>,
  'analisis-de-proyectos': <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m14.5 14.5 5 5M7 10h6M10 7v6"/></svg>,
  ingenieria: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M14.7 6.3a4 4 0 0 0-5 5L3 18l3 3 6.7-6.7a4 4 0 0 0 5-5l-3 3-3-3 3-3Z"/></svg>,
  'montajes-y-puesta-en-marcha': <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M4 20h16M6 20V9l6-4 6 4v11M9 20v-5h6v5M9 10h.01M15 10h.01"/></svg>,
  'operacion-y-mantenimiento': <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M12 3a9 9 0 1 0 9 9"/><path d="M12 7v5l3 2M17 3h4v4"/></svg>,
  'ambiental-y-sustentabilidad': <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M20 4C12 4 5 8 5 14c0 3 2 5 5 5 6 0 10-7 10-15Z"/><path d="M4 20c3-5 7-8 12-11"/></svg>,
}

function Reveal({ children, className = '' }: { children: (visible: boolean) => ReactNode; className?: string }) { const { ref, isInView } = useInView(0.15, true); return <div ref={ref} className={className}>{children(isInView)}</div> }
const reveal = (visible: boolean) => `transition-all duration-700 ease-out motion-reduce:transform-none motion-reduce:transition-none ${visible ? 'translate-y-0 opacity-100' : 'translate-y-8 opacity-0'}`

export function ServiciosHubPage() {
  return <main>
    <section className="relative flex min-h-[500px] items-center bg-[url('https://cdn-enerbio.misionary.com.ar/Banners/BannerWeb.webp')] bg-cover bg-center text-white md:min-h-[55vh]"><div className="absolute inset-0 bg-enerbio-verde-oscuro/82" /><div className="relative mx-auto w-full max-w-7xl px-4 py-24 md:px-6 lg:px-8"><p className="animate-fade-in text-sm font-semibold uppercase tracking-[0.2em] text-enerbio-verde-claro">Nuestros servicios</p><h1 className="animate-fade-up delay-200 mt-5 max-w-4xl text-4xl font-bold leading-tight md:text-6xl">Soluciones energéticas integrales, contratables a tu medida</h1><p className="animate-fade-in delay-500 mt-7 max-w-2xl text-lg leading-8 text-white/90 md:text-xl">Desde el análisis hasta la operación diaria, podés contratar servicios individuales, combinarlos o delegar el ciclo completo.</p></div></section>

    <section className="bg-white py-24 md:py-32"><Reveal className="mx-auto max-w-7xl px-4 md:px-6 lg:px-8">{(visible) => <><div className={`${reveal(visible)} mx-auto max-w-3xl text-center`}><p className="text-sm font-semibold uppercase tracking-[0.2em] text-enerbio-verde-acento">Cómo contratar</p><h2 className="mt-4 text-4xl font-bold text-enerbio-azul-gris md:text-5xl">Tres formas de trabajar con nosotros</h2><p className="mt-6 text-lg leading-8 text-enerbio-gris-texto">Nos adaptamos a la escala y necesidades de cada proyecto.</p></div><div className="mt-14 grid gap-6 lg:grid-cols-3">{modes.map(([icon,title,text,example], index) => <article key={title} className={`${reveal(visible)} rounded-2xl bg-[#F8F8F8] p-8 shadow-sm`} style={{transitionDelay:`${140+index*140}ms`}}><span className="flex h-14 w-14 items-center justify-center rounded-lg bg-enerbio-verde-oscuro p-3.5 text-white">{icons[icon]}</span><h3 className="mt-6 text-2xl font-bold text-enerbio-verde-oscuro">{title}</h3><p className="mt-4 leading-7 text-enerbio-gris-texto">{text}</p><p className="mt-6 border-t border-gray-200 pt-4 text-sm font-semibold text-enerbio-azul-gris">{example}</p>{index === 2 && <Link href="/vapor-y-energia" className="mt-5 inline-block font-semibold text-enerbio-verde-oscuro">Conocé Vapor y Energía →</Link>}</article>)}</div></>}</Reveal></section>

    <section className="bg-gradient-to-br from-enerbio-verde-oscuro to-enerbio-azul-gris py-24 text-white md:py-32"><Reveal className="mx-auto grid max-w-7xl items-center gap-12 px-4 md:px-6 lg:grid-cols-[3fr_2fr] lg:px-8">{(visible) => <><div><span className={`${reveal(visible)} inline-flex rounded-full bg-enerbio-verde-acento px-4 py-2 text-xs font-semibold uppercase tracking-widest`}>Nuestro modelo insignia</span><h2 className={`${reveal(visible)} mt-6 text-5xl font-bold md:text-6xl`} style={{transitionDelay:'120ms'}}>Vapor y Energía</h2><p className={`${reveal(visible)} mt-5 text-xl text-enerbio-verde-claro md:text-2xl`} style={{transitionDelay:'240ms'}}>Comprás energía y vapor. Nosotros nos encargamos de todo lo demás.</p><p className={`${reveal(visible)} mt-6 max-w-2xl leading-7 text-white/85`} style={{transitionDelay:'360ms'}}>EnerBio desarrolla, financia, construye y opera la planta. Vos pagás por lo consumido, sin inversión inicial y con previsibilidad de largo plazo.</p><div className={`${reveal(visible)} mt-9`} style={{transitionDelay:'480ms'}}><EnerBioButtonAccent href="/vapor-y-energia" className="text-white">Conocé Vapor y Energía →</EnerBioButtonAccent></div></div><div className="grid grid-cols-2 gap-3">{benefits.map((benefit,index)=><div key={benefit} className={`${reveal(visible)} rounded-lg border border-white/15 bg-white/10 p-4 text-sm font-semibold`} style={{transitionDelay:`${180+index*80}ms`}}>{benefit}</div>)}</div></>}</Reveal></section>

    <section className="bg-[#F8F8F8] py-24 md:py-32"><Reveal className="mx-auto max-w-7xl px-4 md:px-6 lg:px-8">{(visible)=><><div className={`${reveal(visible)} max-w-3xl`}><p className="text-sm font-semibold uppercase tracking-[0.2em] text-enerbio-verde-acento">Nuestros departamentos</p><h2 className="mt-4 text-4xl font-bold text-enerbio-azul-gris md:text-5xl">Cinco áreas especializadas al servicio de tu proyecto</h2><p className="mt-6 text-lg leading-8 text-enerbio-gris-texto">Cada departamento es autónomo. Podés contratar uno, varios o todos.</p></div><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{servicePages.map((service,index)=><Link key={service.slug} href={`/servicios/${service.slug}`} className={`${reveal(visible)} group flex min-h-72 flex-col rounded-2xl bg-white p-8 shadow-sm transition-shadow hover:shadow-xl`} style={{transitionDelay:`${120+index*100}ms`}}><span className="flex h-14 w-14 items-center justify-center rounded-lg bg-enerbio-verde-acento p-3.5 text-white transition-colors group-hover:bg-enerbio-verde-oscuro">{icons[service.slug]}</span><h3 className="mt-6 text-2xl font-bold text-enerbio-verde-oscuro">{service.eyebrow}</h3><p className="mt-4 flex-1 leading-7 text-enerbio-gris-texto">{service.intro}</p><span className="mt-6 font-semibold text-enerbio-azul-gris transition-transform group-hover:translate-x-1">Ver servicio →</span></Link>)}</div></>}</Reveal></section>

    <section className="bg-white py-20 text-center md:py-24"><Reveal className="mx-auto max-w-3xl px-4">{(visible)=><><h2 className={`${reveal(visible)} text-4xl font-bold text-enerbio-azul-gris md:text-5xl`}>¿No estás seguro qué servicio necesitás?</h2><p className={`${reveal(visible)} mt-5 text-lg leading-8 text-enerbio-gris-texto`} style={{transitionDelay:'140ms'}}>Evaluamos tu proyecto y proponemos la mejor combinación para tu caso.</p><div className={`${reveal(visible)} mt-9`} style={{transitionDelay:'280ms'}}><EnerBioButtonPrimary href="/contacto">Consultanos gratis →</EnerBioButtonPrimary></div></>}</Reveal></section>
  </main>
}