'use client'

import type { ReactNode } from 'react'
import { EnerBioButtonAccent, EnerBioButtonSecondary } from '@/components/ui/EnerBioButton'
import { ServiceIcon, type ServiceIconName } from '@/components/ui/ServiceIcon'
import { useInView } from '@/lib/hooks/useInView'

const steps: [ServiceIconName, string, string][] = [
  ['design', 'Análisis y diseño', 'Evaluamos las necesidades energéticas y térmicas y diseñamos la planta ideal para tu industria.'],
  ['construction', 'Financiamiento y construcción', 'EnerBio financia el proyecto y ejecuta la ingeniería, el montaje y la puesta en marcha.'],
  ['operation', 'Operación 24/7', 'Nuestro equipo opera la planta mientras tu proceso recibe vapor y energía de manera continua.'],
  ['contract', 'Compromiso de largo plazo', 'El suministro se estructura con precios estables y pago por consumo durante el contrato.'],
]
const benefits: [ServiceIconName, string, string][] = [
  ['savings', 'Sin CAPEX', 'EnerBio financia la infraestructura y libera tu capital para el core del negocio.'],
  ['predictability', 'Costos predecibles', 'Tarifas estables que reducen la incertidumbre de los costos energéticos.'],
  ['operation', 'Sin operación propia', 'No necesitás personal técnico ni logística de mantenimiento.'],
  ['environment', 'Energía renovable', 'Reducís la huella de carbono y avanzás en tus compromisos ambientales.'],
  ['maintenance', 'Riesgo transferido', 'EnerBio asume el riesgo tecnológico, operativo y de mantenimiento.'],
  ['focus', 'Foco en tu negocio', 'Delegás la energía a especialistas y concentrás recursos en tu operación.'],
]
const comparison = [
  ['Inversión inicial', 'Alta', '$0'], ['Propiedad de la planta', 'Tu empresa', 'EnerBio'], ['Personal técnico', 'Equipo propio', 'Lo asume EnerBio'],
  ['Riesgo tecnológico', 'Tu empresa', 'EnerBio'], ['Costos operativos', 'Variables', 'Estables'], ['Mantenimiento', 'A tu cargo', 'A cargo de EnerBio'],
  ['Tiempo hasta operación', '18–24 meses', 'Sin gestión del cliente'], ['Huella de carbono', 'Depende del combustible', '100% renovable'],
]
const industries: [ServiceIconName, string, string][] = [
  ['agriculture', 'Molinos y agroindustria', 'Alto consumo térmico y eléctrico.'], ['cold', 'Frigoríficos', 'Vapor de proceso y residuos aprovechables.'],
  ['dairy', 'Industria láctea', 'Demanda térmica y potencial de biogás.'], ['ethanol', 'Producción de etanol', 'Cogeneración a partir de biomasa.'],
  ['forestry', 'Aserraderos', 'Biomasa forestal y vapor para secado.'], ['industry', 'Industrias intensivas en vapor', 'Suministro continuo para procesos críticos.'],
]
const faqs = [
  ['¿Qué pasa si mi consumo baja?', 'Cada contrato se estructura con condiciones flexibles considerando variaciones estacionales y cambios operativos.'],
  ['¿Qué combustible usa la planta?', 'Depende del proyecto: biomasa forestal, biogás de efluentes o una combinación con solar.'],
  ['¿Qué pasa al finalizar el contrato?', 'Se puede renovar, transferir la planta al cliente o acordar su desmantelamiento por EnerBio.'],
  ['¿Puedo escalar la producción?', 'Sí. La capacidad puede ampliarse a medida que crece la demanda energética.'],
]

function Reveal({ children, className = '' }: { children: (visible: boolean) => ReactNode; className?: string }) { const { ref, isInView } = useInView(0.12, true); return <div ref={ref} className={className}>{children(isInView)}</div> }
const reveal = (visible: boolean) => `transition-all duration-700 ease-out motion-reduce:transform-none motion-reduce:transition-none ${visible ? 'translate-y-0 opacity-100' : 'translate-y-8 opacity-0'}`

export function VaporEnergiaPage() {
  return <main>
    <section className="relative flex min-h-[70vh] items-center overflow-hidden bg-[url('https://cdn-enerbio.misionary.com.ar/Banners/BannerWeb.webp')] bg-cover bg-center text-white"><div className="absolute inset-0 bg-gradient-to-r from-enerbio-verde-oscuro/95 to-enerbio-azul-gris/75" /><div className="relative mx-auto w-full max-w-7xl px-4 py-28 md:px-6 lg:px-8"><span className="animate-fade-in inline-flex rounded-full bg-enerbio-verde-acento px-4 py-2 text-xs font-semibold uppercase tracking-widest">Nuestro modelo insignia</span><h1 className="animate-fade-up delay-200 mt-7 text-6xl font-bold md:text-7xl lg:text-8xl">Vapor y Energía</h1><p className="animate-fade-in delay-500 mt-6 max-w-3xl text-xl leading-8 text-enerbio-verde-claro md:text-2xl">Comprás energía y vapor. Nosotros nos encargamos de todo lo demás.</p><p className="animate-fade-in delay-500 mt-5 max-w-2xl leading-7 text-white/85">EnerBio desarrolla, financia, construye y opera la planta. Vos pagás por lo que consumís, con previsibilidad y sin inversión inicial.</p><div className="animate-fade-up delay-800 mt-9 flex flex-col gap-4 sm:flex-row"><EnerBioButtonAccent href="/contacto" className="text-white">Analicemos tu caso</EnerBioButtonAccent><EnerBioButtonSecondary href="#casos">Ver casos de éxito</EnerBioButtonSecondary></div></div></section>

    <section className="bg-white py-24 md:py-32"><Reveal className="mx-auto grid max-w-7xl items-center gap-12 px-4 md:px-6 lg:grid-cols-2 lg:px-8">{(visible)=><><div><p className={`${reveal(visible)} text-sm font-semibold uppercase tracking-[0.2em] text-enerbio-verde-acento`}>El modelo</p><h2 className={`${reveal(visible)} mt-4 text-4xl font-bold leading-tight text-enerbio-azul-gris md:text-5xl`} style={{transitionDelay:'120ms'}}>Toda la infraestructura energética, sin inversión inicial</h2><p className={`${reveal(visible)} mt-7 text-lg leading-8 text-enerbio-gris-texto`} style={{transitionDelay:'240ms'}}>Vapor y Energía es un modelo BOO donde EnerBio diseña, financia, construye, opera y mantiene la planta. Tu empresa solo paga por el vapor y la energía consumidos.</p><ul className={`${reveal(visible)} mt-7 space-y-3 text-enerbio-gris-texto`} style={{transitionDelay:'360ms'}}>{['Planta diseñada a medida','Financiamiento de la inversión','Construcción y puesta en marcha','Operación y mantenimiento 24/7'].map(item=><li key={item} className="flex gap-3"><span className="font-bold text-enerbio-verde-acento">✓</span>{item}</li>)}</ul></div><div className={`${reveal(visible)} grid aspect-square place-items-center rounded-2xl bg-enerbio-azul-gris p-10 text-center text-white`} style={{transitionDelay:'180ms'}}><div><p className="font-montserrat text-7xl font-bold text-enerbio-verde-acento">BOO</p><p className="mt-4 text-xl font-semibold">Build · Own · Operate</p><p className="mt-3 text-white/70">EnerBio asume la infraestructura completa</p></div></div></>}</Reveal></section>

    <section className="bg-[#F8F8F8] py-24 md:py-32"><Reveal className="mx-auto max-w-7xl px-4 md:px-6 lg:px-8">{(visible)=><><div className={`${reveal(visible)} max-w-3xl`}><p className="text-sm font-semibold uppercase tracking-[0.2em] text-enerbio-verde-acento">Cómo funciona</p><h2 className="mt-4 text-4xl font-bold text-enerbio-azul-gris md:text-5xl">Un proceso simple, un compromiso de largo plazo</h2></div><div className="mt-14 grid gap-5 lg:grid-cols-4">{steps.map(([icon,title,text],index)=><article key={title} className={`${reveal(visible)} bg-white p-7 shadow-sm`} style={{transitionDelay:`${120+index*110}ms`}}><span className="flex h-14 w-14 items-center justify-center rounded-lg bg-enerbio-verde-acento p-3.5 text-white"><ServiceIcon name={icon} className="h-full w-full" /></span><h3 className="mt-6 text-xl font-bold text-enerbio-verde-oscuro">{title}</h3><p className="mt-4 text-sm leading-6 text-enerbio-gris-texto">{text}</p></article>)}</div></>}</Reveal></section>

    <section className="bg-white py-24 md:py-32"><Reveal className="mx-auto max-w-7xl px-4 md:px-6 lg:px-8">{(visible)=><><div className={`${reveal(visible)} max-w-3xl`}><p className="text-sm font-semibold uppercase tracking-[0.2em] text-enerbio-verde-acento">Beneficios</p><h2 className="mt-4 text-4xl font-bold text-enerbio-azul-gris md:text-5xl">Por qué elegir Vapor y Energía</h2></div><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{benefits.map(([icon,title,text],index)=><article key={title} className={`${reveal(visible)} rounded-2xl bg-[#F8F8F8] p-8`} style={{transitionDelay:`${100+index*90}ms`}}><span className="flex h-12 w-12 items-center justify-center rounded-full bg-enerbio-verde-oscuro p-3 text-white"><ServiceIcon name={icon} className="h-full w-full" /></span><h3 className="mt-6 text-xl font-bold text-enerbio-verde-oscuro">{title}</h3><p className="mt-3 leading-7 text-enerbio-gris-texto">{text}</p></article>)}</div></>}</Reveal></section>

    <section className="bg-enerbio-azul-gris py-24 text-white md:py-32"><Reveal className="mx-auto max-w-6xl px-4 md:px-6">{(visible)=><><h2 className={`${reveal(visible)} text-4xl font-bold md:text-5xl`}>Modelo tradicional vs Vapor y Energía</h2><div className={`${reveal(visible)} mt-12 overflow-x-auto rounded-2xl bg-white`} style={{transitionDelay:'160ms'}}><table className="w-full min-w-[680px] text-left text-enerbio-gris-texto"><thead><tr className="bg-enerbio-verde-oscuro text-white"><th className="p-5">Aspecto</th><th className="p-5">Modelo tradicional</th><th className="p-5 text-enerbio-verde-claro">Vapor y Energía</th></tr></thead><tbody>{comparison.map(([aspect,traditional,enerbio])=><tr key={aspect} className="border-b border-gray-200 last:border-0"><th className="p-5 font-semibold text-enerbio-verde-oscuro">{aspect}</th><td className="p-5">{traditional}</td><td className="p-5 font-semibold text-enerbio-verde-oscuro">{enerbio}</td></tr>)}</tbody></table></div></>}</Reveal></section>

    <section className="bg-[#F8F8F8] py-24 md:py-32"><Reveal className="mx-auto max-w-7xl px-4 md:px-6 lg:px-8">{(visible)=><><div className={`${reveal(visible)} max-w-3xl`}><p className="text-sm font-semibold uppercase tracking-[0.2em] text-enerbio-verde-acento">Industrias</p><h2 className="mt-4 text-4xl font-bold text-enerbio-azul-gris md:text-5xl">Diseñado para operaciones con alto consumo energético</h2></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{industries.map(([icon,title,text],index)=><article key={title} className={`${reveal(visible)} flex gap-4 bg-white p-6 shadow-sm`} style={{transitionDelay:`${100+index*80}ms`}}><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-enerbio-verde-acento p-2.5 text-white"><ServiceIcon name={icon} className="h-full w-full" /></span><div><h3 className="font-bold text-enerbio-verde-oscuro">{title}</h3><p className="mt-2 text-sm leading-6 text-enerbio-gris-texto">{text}</p></div></article>)}</div></>}</Reveal></section>

    <section id="casos" className="bg-white py-24 md:py-28"><Reveal className="mx-auto max-w-7xl px-4 md:px-6 lg:px-8">{(visible)=><div className={`${reveal(visible)} grid gap-8 rounded-2xl border border-dashed border-enerbio-verde-acento bg-[#F8F8F8] p-8 md:grid-cols-[2fr_3fr] md:p-12`}><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-enerbio-verde-acento">Casos de éxito</p><h2 className="mt-4 text-3xl font-bold text-enerbio-azul-gris md:text-4xl">Proyectos bajo el modelo</h2></div><div><p className="text-lg leading-8 text-enerbio-gris-texto">Los casos operados específicamente bajo Vapor y Energía están en proceso de validación comercial. Se publicarán cuando el alcance contractual esté confirmado.</p></div></div>}</Reveal></section>

    <section className="bg-[#F8F8F8] py-24 md:py-28"><Reveal className="mx-auto max-w-4xl px-4 md:px-6">{(visible)=><><h2 className={`${reveal(visible)} text-4xl font-bold text-enerbio-azul-gris md:text-5xl`}>Preguntas frecuentes</h2><div className="mt-10 space-y-3">{faqs.map(([question,answer],index)=><details key={question} className={`${reveal(visible)} group rounded-lg bg-white p-6`} style={{transitionDelay:`${100+index*90}ms`}}><summary className="cursor-pointer list-none pr-8 text-lg font-bold text-enerbio-verde-oscuro">{question}<span className="float-right transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 leading-7 text-enerbio-gris-texto">{answer}</p></details>)}</div></>}</Reveal></section>

    <section className="bg-enerbio-verde-oscuro py-24 text-center text-white"><Reveal className="mx-auto max-w-3xl px-4">{(visible)=><><h2 className={`${reveal(visible)} text-4xl font-bold md:text-5xl`}>¿Tu industria consume mucha energía y vapor?</h2><p className={`${reveal(visible)} mt-5 text-lg leading-8 text-white/80`} style={{transitionDelay:'140ms'}}>Evaluemos si este modelo puede transformar tus costos energéticos en una solución predecible y sostenible.</p><div className={`${reveal(visible)} mt-9`} style={{transitionDelay:'280ms'}}><EnerBioButtonAccent href="/contacto" className="text-white">Analicemos tu caso →</EnerBioButtonAccent></div></>}</Reveal></section>
  </main>
}